/**
 * Webview UI strings, following the VSCode display language (ADR D13).
 * The ja dictionary is ported from the frozen v7 STR table; data and file
 * field names stay English in both languages (v7 policy).
 *
 * The extension injects the locale as `data-locale` on the webview root;
 * main.ts calls initLocale() before the app builds any DOM.
 */

const EN = {
  tb_phys: 'Physical',
  tb_logi: 'Logical',
  tb_under: 'Underlay',
  tb_global: 'Global',
  tb_snap: 'Snap',
  tb_grid: 'Grid',
  tb_fit: 'Fit',
  tt_seg: 'Physical view: cables & circuits. Logical view: VRF instances inside devices.',
  tt_under: 'Underlay — show the physical links faintly under the logical view',
  tt_global: 'Global — show/hide the global-routing-table compartments',
  tt_snap: 'Grid snap — while ON, dragged nodes snap to a 10px grid',
  tt_grid: 'Grid lines — show/hide the background grid',
  tt_fit: 'Fit view — zoom to show everything',
  tt_zoom_in: 'Zoom in',
  tt_zoom_out: 'Zoom out',
  tt_zoom_reset: 'Zoom to 100%',
  tb_new: 'New',
  tt_new: 'New topology file — pick a template (built-in or from your templates folder)',
  tb_export: 'Export',
  tt_export: 'Export — Markdown / For AI / import schema / draw.io (the file itself is the JSON)',
  ex_md: 'Markdown',
  ex_ai: 'For AI',
  ex_schema: 'Schema (for AI agents)',
  ex_drawio: 'draw.io',
  tb_agent_guide: 'AI Guide',
  tt_agent_guide: 'Teach AI agents how to edit this file (writes AGENTS.md)',
  gm_title: 'AI Agent Guide',
  gm_body:
    '<p>Coding agents (Claude Code, Copilot, …) can edit this <b>*.topo.json</b> file as text while the canvas follows. To do that reliably they need to know the file format first.</p>' +
    '<p>This writes an <b>AGENTS.md</b> file into the workspace root containing the editing rules, the full JSON Schema, and an example — the place most coding agents read automatically <b>before</b> they edit. Once written, just ask your agent things like <i>“assign IP addresses to VRF-001”</i> and it will use the right fields (e.g. <code>ip_address</code>).</p>',
  gm_exists_note:
    '<b>If AGENTS.md already exists, it is NOT overwritten:</b> the TopoDraft section (between marker comments) is appended or updated in place — everything else in the file stays untouched. Rerunning is always safe.',
  gm_write: 'Write AGENTS.md',
  gm_saveas: 'Save as…',
  tt_gm_saveas: 'Write the guide to a different file instead of AGENTS.md',
  empty_hint: 'The canvas is empty<br><b>Drag a node from the left palette</b> — or edit the JSON as text',
  err_invalid: 'Invalid JSON',
  t_snap_on: 'Grid snap ON — positions snap to a 10px grid',
  t_snap_off: 'Grid snap OFF — free positioning',
  t_cleared: 'Canvas cleared — Ctrl+Z to undo',
  t_copied: 'Copied {n} node(s) / {m} link(s)',
  t_log_link: 'Logical link: {a} [{va}] — {b} [{vb}]',
  t_global_word: 'global',
  t_circuit: 'Connected as circuit',
  t_cable: 'Connected as cable',
  st_devices: 'devices',
  st_pn: 'provider nets',
  st_networks: 'segments',
  st_links: 'links',
  st_sites: 'sites',
  st_sel: 'selected',
  pn_paused:
    'The document has a JSON error — the canvas shows the last valid state and editing is paused until the text parses again.',
  home_title: 'TopoDraft',
  home_info:
    '<b>Physical</b> shows cables and carrier circuits; <b>Logical</b> shows VRF compartments connected by logical links.<br><br>Drag from a node\'s <b>◦ port</b> to connect. <b>Shift</b>+click or <b>Shift</b>+drag to multi-select. Double-click renames. Right-click for the context menu.<br><br><b>Ctrl/Cmd+C/V/D</b> copy · paste · duplicate — <b>Del</b> delete — <b>arrows</b> nudge — undo/redo is VSCode\'s regular <b>Ctrl/Cmd+Z</b>.',
  sel_title: 'Selection',
  badge_nodes: '{n} nodes',
  bulk_label: 'set site for all selected devices',
  bulk_ph: 'site name…',
  bulk_apply: 'Apply site',
  arrange: 'Arrange',
  al_row: '═ Row',
  al_col: '║ Column',
  al_dh: '↔ Distribute',
  al_dv: '↕ Distribute',
  tt_row: 'Same Y — align in one horizontal row',
  tt_col: 'Same X — align in one vertical column',
  tt_dh: 'Even horizontal spacing (3+ nodes)',
  tt_dv: 'Even vertical spacing (3+ nodes)',
  copy: 'Copy',
  dup: 'Duplicate',
  del: 'Delete',
  del_link: 'Delete link',
  pn_title2: 'Provider network',
  pn_badge: 'circuit endpoint',
  pn_info:
    'A provider network is a carrier-side network (DX, FastConnect, IP-VPN cloud …). Links attached to it are always <b>circuits</b>. In the file it lives in <b>provider_networks[]</b>.',
  dev_title: 'Device',
  vrf_title: 'VRF instances',
  vrf_none: 'Only the global routing table',
  vrf_ph: 'Add VRF (e.g. PROD)',
  vrf_add: 'Add',
  vrf_chip_derived: 'defined by an interface or logical link',
  vrf_chip: 'routing instance',
  vrf_chip_del: 'Remove VRF',
  if_title: 'Interfaces',
  if_none: 'None yet — subinterfaces (Gi0/0/1.100), LAG parents (lag) and VRFs are supported',
  if_add: '+ Add interface',
  cc_title: 'Config Context',
  cc_edit: 'Edit config context (JSON)',
  log_title: 'Logical link',
  log_badge: 'L3 / VRF',
  phy_title: 'Physical link',
  badge_cable: 'Cable / local',
  badge_circuit: 'Circuit / carrier',
  ep_vrf: 'VRF (empty = global)',
  ep_id: 'ID (tenant / attach …)',
  ep_id_pn: 'ID (attachment / VC / VIF …)',
  ep_if: 'interface (subIF ok)',
  ep_ip: 'ip_address',
  ep_no_site: '(no site)',
  ep_missing: 'missing device',
  ep_unresolved: '(unresolved)',
  log_note:
    'With an interface set, the ip_address is written to that interface on the device (created if missing). Without one, the IP stays on this endpoint.',
  seg_pn_dis: 'Provider-network links must be circuits',
  cm_rename: 'Rename',
  cm_cc: 'Config context…',
  cm_role: 'Change role',
  cm_del_n: 'Delete {n} nodes',
  cm_selected: '{n} nodes selected',
  cm_align_row: 'Align in a row',
  cm_align_col: 'Align in a column',
  cm_dist_h: 'Distribute horizontally',
  cm_dist_v: 'Distribute vertically',
  cm_to_circuit: 'Change to circuit',
  cm_to_cable: 'Change to cable',
  cm_add_here: 'Add node here',
  cm_paste: 'Paste here',
  cm_select_all: 'Select all',
  clear_canvas: 'Clear canvas',
  pal_nodes: 'Nodes',
  pal_hint:
    'Drag onto the canvas to place.<br>Connect: drag from a <b>◦ port</b> shown on hover.<br><kbd>Shift</kbd>+click / drag: multi-select',
  pal_router: 'Router',
  pal_switch: 'Switch',
  pal_firewall: 'Firewall',
  pal_extpeer: 'External peer',
  pal_server: 'Server',
  pal_pn: 'Provider network',
  pal_networkseg: 'Network segment',
  pal_generic: 'Generic node',
  net_title: 'Network segment',
  net_badge: 'multi-access',
  fhrp_title: 'FHRP (HSRP / VRRP)',
  net_info:
    'A multi-access L3 segment (e.g. a /28 shared by several routers). Attach devices by dragging from a VRF compartment onto this node — each attachment is one logical link. Real IPs stay on the device interfaces; the virtual IP lives here in fhrp.',
  t_seg_logical: 'Network segments live in the logical view — switched.',
  cc_modal: 'Config Context',
  m_cc_note:
    'Free-form structured settings for this device (JSON object). Stored as devices[].config_context and re-emitted verbatim. Save with empty text to clear.',
  m_save: 'Save',
  m_cancel: 'Cancel',
  t_cc_obj: 'Top level must be an object (key/value map)',
  t_cc_err: 'Parse error: ',
} as const;

export type StringKey = keyof typeof EN;

const JA: Record<StringKey, string> = {
  tb_phys: '物理',
  tb_logi: '論理',
  tb_under: '物理を薄く表示',
  tb_global: 'global',
  tb_snap: 'スナップ',
  tb_grid: 'グリッド',
  tb_fit: '全体表示',
  tt_seg: '物理ビュー: ケーブルと回線。論理ビュー: デバイス内のVRFインスタンスを論理リンクで接続。',
  tt_under: '物理リンクを論理ビューの下に薄く表示',
  tt_global: '論理ビューでglobal(グローバルルーティングテーブル)区画の表示/非表示',
  tt_snap: 'グリッドスナップ — ONの間、ノードは10pxグリッドに吸着します',
  tt_grid: 'グリッド線 — 背景グリッドの表示/非表示',
  tt_fit: '全体表示 — 全ノードが収まるようにズーム',
  tt_zoom_in: 'ズームイン',
  tt_zoom_out: 'ズームアウト',
  tt_zoom_reset: 'ズームを100%に',
  tb_new: '新規',
  tt_new: '新しいトポロジファイル — テンプレートを選択して作成 (ビルトイン / ユーザーテンプレート)',
  tb_export: 'エクスポート',
  tt_export: 'エクスポート — Markdown / AI向け / インポートスキーマ / draw.io (JSON自体がこのファイルです)',
  ex_md: 'Markdown',
  ex_ai: 'AI向け',
  ex_schema: 'スキーマ (AIエージェント用)',
  ex_drawio: 'draw.io',
  tb_agent_guide: 'AIガイド',
  tt_agent_guide: 'AIエージェントにこのファイルの編集方法を教える (AGENTS.md を書き出し)',
  gm_title: 'AIエージェント用ガイド',
  gm_body:
    '<p>コーディングエージェント(Claude Code、Copilot など)は、この <b>*.topo.json</b> をテキストとして編集でき、キャンバスが追従します。そのためには、エージェントが先にファイル形式を知っている必要があります。</p>' +
    '<p>このボタンは、編集ルール・JSON Schema 全文・サンプルをまとめた <b>AGENTS.md</b> をワークスペース直下に書き出します。多くのエージェントは編集の<b>前に</b>この場所を自動で読みます。書き出した後は「VRF-001 に IP をアサインして」のように普通に依頼するだけで、正しいフィールド名(例: <code>ip_address</code>)で編集してくれます。</p>',
  gm_exists_note:
    '<b>既に AGENTS.md がある場合、上書きはされません:</b> マーカーコメントで囲まれた TopoDraft セクションだけが末尾への追記または置き換えで更新され、それ以外の内容には一切触れません。何度実行しても安全です。',
  gm_write: 'AGENTS.md に書き出す',
  gm_saveas: '別名で保存…',
  tt_gm_saveas: 'AGENTS.md ではなく別のファイルにガイドを書き出します',
  empty_hint: 'キャンバスは空です<br><b>左のパレットからノードをドラッグ</b>するか、テキストとしてJSONを編集してください',
  err_invalid: 'JSONが不正です',
  t_snap_on: 'グリッドスナップ ON — 10pxグリッドに吸着します',
  t_snap_off: 'グリッドスナップ OFF — 自由配置',
  t_cleared: 'キャンバスをクリアしました — Ctrl+Zで戻せます',
  t_copied: '{n} ノード / {m} リンクをコピーしました',
  t_log_link: '論理リンク: {a} [{va}] — {b} [{vb}]',
  t_global_word: 'global',
  t_circuit: 'circuitとして接続しました',
  t_cable: 'cableとして接続しました',
  st_devices: 'デバイス',
  st_pn: 'プロバイダ網',
  st_networks: 'セグメント',
  st_links: 'リンク',
  st_sites: 'サイト',
  st_sel: '選択中',
  pn_paused:
    'ドキュメントにJSONエラーがあります — キャンバスは最後の正常な状態を表示しており、テキストが解析できるようになるまで編集は一時停止します。',
  home_title: 'TopoDraft',
  home_info:
    '<b>物理</b>はケーブルとキャリア回線、<b>論理</b>は論理リンクで接続されたVRF区画を表示します。<br><br>ノードの<b>◦ ポート</b>からドラッグして接続。<b>Shift</b>+クリック / <b>Shift</b>+ドラッグで複数選択。ダブルクリックで名前変更。右クリックでコンテキストメニュー。<br><br><b>Ctrl/Cmd+C/V/D</b> コピー・貼り付け・複製 — <b>Del</b> 削除 — <b>矢印</b> 微調整 — 元に戻す/やり直すは VSCode 標準の <b>Ctrl/Cmd+Z</b> です。',
  sel_title: '選択',
  badge_nodes: '{n} ノード',
  bulk_label: '選択中の全デバイスにサイトを設定',
  bulk_ph: 'サイト名…',
  bulk_apply: 'サイトを適用',
  arrange: '整列',
  al_row: '═ 横一列',
  al_col: '║ 縦一列',
  al_dh: '↔ 等間隔',
  al_dv: '↕ 等間隔',
  tt_row: 'Y座標を揃えて横一列に',
  tt_col: 'X座標を揃えて縦一列に',
  tt_dh: '水平方向に等間隔配置(3ノード以上)',
  tt_dv: '垂直方向に等間隔配置(3ノード以上)',
  copy: 'コピー',
  dup: '複製',
  del: '削除',
  del_link: 'リンクを削除',
  pn_title2: 'プロバイダ網',
  pn_badge: '回線の終端',
  pn_info:
    'プロバイダ網はキャリア側のネットワークです(DX、FastConnect、IP-VPN網など)。接続されるリンクは常に<b>circuit</b>になります。ファイルでは <b>provider_networks[]</b> に格納されます。',
  dev_title: 'デバイス',
  vrf_title: 'VRF インスタンス',
  vrf_none: 'グローバルルーティングテーブルのみ',
  vrf_ph: 'VRFを追加 (例: PROD)',
  vrf_add: '追加',
  vrf_chip_derived: 'インターフェイスまたは論理リンクで定義',
  vrf_chip: 'ルーティングインスタンス',
  vrf_chip_del: 'VRFを削除',
  if_title: 'インターフェイス',
  if_none: '未登録 — サブIF (Gi0/0/1.100)、LAG親 (lag)、VRF に対応',
  if_add: '+ インターフェイスを追加',
  cc_title: 'Config Context',
  cc_edit: 'Config Contextを編集 (JSON)',
  log_title: '論理リンク',
  log_badge: 'L3 / VRF',
  phy_title: '物理リンク',
  badge_cable: 'ケーブル / 構内',
  badge_circuit: '回線 / キャリア',
  ep_vrf: 'VRF (空 = global)',
  ep_id: 'ID (テナント / アタッチ等)',
  ep_id_pn: 'ID (アタッチメント / VC / VIF等)',
  ep_if: 'interface (サブIF可)',
  ep_ip: 'ip_address',
  ep_no_site: '(サイトなし)',
  ep_missing: 'デバイスが見つかりません',
  ep_unresolved: '(未解決)',
  log_note:
    'interfaceを指定するとIPアドレスはデバイス側のそのインターフェイスに書き込まれます(なければ自動作成)。未指定ならIPはこのエンドポイントに保持されます。',
  seg_pn_dis: 'プロバイダ網へのリンクはcircuit固定です',
  cm_rename: '名前を変更',
  cm_cc: 'Config Context…',
  cm_role: 'ロールを変更',
  cm_del_n: '{n} ノードを削除',
  cm_selected: '{n} ノードを選択中',
  cm_align_row: '横一列に整列',
  cm_align_col: '縦一列に整列',
  cm_dist_h: '水平方向に等間隔配置',
  cm_dist_v: '垂直方向に等間隔配置',
  cm_to_circuit: 'circuitに変更',
  cm_to_cable: 'cableに変更',
  cm_add_here: 'ここにノードを追加',
  cm_paste: 'ここに貼り付け',
  cm_select_all: 'すべて選択',
  clear_canvas: 'キャンバスをクリア',
  pal_nodes: 'ノード',
  pal_hint:
    'パレットからキャンバスへドラッグで配置。<br>接続: ホバーで表示される<b>◦ ポート</b>からドラッグ。<br><kbd>Shift</kbd>+クリック / ドラッグ: 複数選択',
  pal_router: 'ルーター',
  pal_switch: 'スイッチ',
  pal_firewall: 'ファイアウォール',
  pal_extpeer: '外部ピア',
  pal_server: 'サーバー',
  pal_pn: 'プロバイダ網',
  pal_networkseg: 'ネットワークセグメント',
  pal_generic: '汎用ノード',
  net_title: 'ネットワークセグメント',
  net_badge: 'マルチアクセス',
  fhrp_title: 'FHRP (HSRP / VRRP)',
  net_info:
    'マルチアクセスのL3セグメントです(複数ルータで共有する /28 など)。VRF区画からこのノードへドラッグすると接続され、1接続 = 1論理リンクになります。実IPはデバイスのインターフェイス側に、仮想IP(VIP)はここの fhrp に持たせます。',
  t_seg_logical: 'ネットワークセグメントは論理ビューの要素です — 論理ビューに切り替えました。',
  cc_modal: 'Config Context',
  m_cc_note:
    'このデバイスの自由な構造化設定(JSONオブジェクト)。devices[].config_context として保持され、そのまま再出力されます。空にして保存すると削除されます。',
  m_save: '保存',
  m_cancel: 'キャンセル',
  t_cc_obj: 'トップレベルはオブジェクト(キー/値)にしてください',
  t_cc_err: '解析エラー: ',
};

let current: 'en' | 'ja' = 'en';

/** Set the UI language from the VSCode display language (e.g. 'ja', 'en-US'). */
export function initLocale(locale: string | undefined): void {
  current = locale?.toLowerCase().startsWith('ja') ? 'ja' : 'en';
}

export function currentLocale(): 'en' | 'ja' {
  return current;
}

export function T(key: StringKey): string {
  return current === 'ja' ? JA[key] : EN[key];
}

/** {name}-style substitution: fmt(T('t_copied'), { n: 3, m: 1 }). */
export function fmt(template: string, subs: Record<string, string | number>): string {
  return template.replace(/\{(\w+)\}/g, (match, name: string) =>
    name in subs ? String(subs[name]) : match,
  );
}

/* exported for the dictionary-completeness test */
export const STRINGS_EN = EN;
export const STRINGS_JA = JA;
