/**
 * Webview ⇔ extension-host message contract (plan §4.2).
 *
 * Phase 0 ships types only. Runtime helpers (type guards, the
 * baseVersion-mismatch/echo-suppression logic tested as pure functions,
 * plan §6.2 ⑤) arrive with Phase 1.
 */

/** Host → Webview: the text document changed (or initial load). */
export interface UpdateMessage {
  type: 'update';
  /** Full text of the `.topo.json` document — the source of truth (ADR D1). */
  text: string;
  /** `TextDocument.version` this text corresponds to. */
  docVersion: number;
  /**
   * True when the change originated from this webview's own edit request
   * (echo suppression, plan §4.2-3): the webview then preserves selection
   * and viewport instead of resetting them.
   */
  selfOriginated: boolean;
}

/** Webview → Host: request to replace the document with new serialized text. */
export interface EditMessage {
  type: 'edit';
  /** Full canonical `serialize()` output. */
  text: string;
  /**
   * Document version the edit was computed against. The host applies the
   * edit only if this matches the current document version; otherwise the
   * edit is discarded (plan §4.2-2, stale-state overwrite prevention).
   */
  baseVersion: number;
}

/** Webview → Host: the webview finished loading and requests the initial update. */
export interface ReadyMessage {
  type: 'ready';
}

/** The four v7 Export tabs that survive as commands (plan §4.4, ADR D2). */
export type ExportKind = 'markdown' | 'for-ai' | 'schema' | 'drawio';

/**
 * Webview → Host: the toolbar Export menu was used; the host runs the
 * corresponding export command against this editor's document.
 */
export interface ExportRequestMessage {
  type: 'export';
  kind: ExportKind;
}

/**
 * Webview → Host: the toolbar's AI-guide dialog was confirmed; the host
 * writes the agent guide (AGENTS.md) into the workspace.
 */
export interface AgentGuideRequestMessage {
  type: 'agent-guide';
  /** true → the host asks for a target file instead of writing AGENTS.md */
  saveAs?: boolean;
  /** true → also write the opt-in NetBox sync-notes section */
  netbox?: boolean;
}

/**
 * Webview → Host: a template was chosen in the toolbar's ＋New menu; the
 * host runs the New Topology File command (save dialog → open). Without
 * `template` the command shows its template QuickPick (palette path).
 */
export interface NewFileRequestMessage {
  type: 'new-file';
  /** TemplateItem.key ('builtin:<id>' or 'user:<uri>'). */
  template?: string;
}

/** One entry of the toolbar's ＋New template menu. */
export interface TemplateItem {
  /** 'builtin:<id>' or 'user:<uri>' — round-tripped in NewFileRequestMessage. */
  key: string;
  /** Localized display label (localization happens on the host). */
  label: string;
  description?: string;
}

/** Webview → Host: the ＋New menu was opened; reply with a TemplatesMessage. */
export interface ListTemplatesRequestMessage {
  type: 'list-templates';
}

/** Image export formats (#10). SVG is generated by core genSvg; PNG is the
 *  same SVG rasterized on a canvas inside the webview (the only place a
 *  canvas exists — the desktop extension host is Node). */
export type ImageFormat = 'svg' | 'png';

/**
 * Host → Webview: an image-export command was invoked from the palette;
 * the webview renders its CURRENT view and replies with a SaveImageMessage.
 */
export interface ImageExportRequestMessage {
  type: 'export-image';
  format: ImageFormat;
}

/**
 * Webview → Host: rendered image content; the host shows the save dialog
 * and writes the file (vscode.workspace.fs — web-safe).
 */
export interface SaveImageMessage {
  type: 'save-image';
  format: ImageFormat;
  /** SVG text (format 'svg'). */
  text?: string;
  /** Base64 PNG bytes (format 'png'). */
  dataBase64?: string;
}

/** Host → Webview: current template list for the ＋New menu. */
export interface TemplatesMessage {
  type: 'templates';
  items: TemplateItem[];
}

export type HostToWebviewMessage = UpdateMessage | TemplatesMessage | ImageExportRequestMessage;
export type WebviewToHostMessage =
  | EditMessage
  | ReadyMessage
  | ExportRequestMessage
  | AgentGuideRequestMessage
  | NewFileRequestMessage
  | ListTemplatesRequestMessage
  | SaveImageMessage;
