/**
 * AGENTS.md generator: writes the *.topo.json contract where coding-agent
 * harnesses (Claude Code, Copilot, …) discover instructions automatically.
 * This is how an agent learns the format BEFORE its first edit — the
 * Problems panel (schema + did-you-mean diagnostics) covers the after.
 *
 * Pure string logic here; the command wiring lives in commands.ts.
 */
import { genSchemaDoc } from '@topodraft/core';

export const GUIDE_BEGIN = '<!-- topodraft:agent-guide:begin -->';
export const GUIDE_END = '<!-- topodraft:agent-guide:end -->';
/** Optional, independently managed section — not every user runs NetBox. */
export const NETBOX_BEGIN = '<!-- topodraft:netbox-guide:begin -->';
export const NETBOX_END = '<!-- topodraft:netbox-guide:end -->';

export function buildAgentGuideSection(): string {
  return `${GUIDE_BEGIN}
<!-- Generated by the TopoDraft VSCode extension. Do not edit between these
     markers — rerun "TopoDraft: Write AI Agent Guide (AGENTS.md)" to update. -->

# Editing *.topo.json files (TopoDraft)

Files matching \`*.topo.json\` are network topology documents edited BOTH by
humans on the TopoDraft canvas and by agents as text. The text document is
the single source of truth — your edits appear on the canvas live.

When asked to create, draw, or update a NETWORK DIAGRAM or topology in this
workspace, produce a \`*.topo.json\` file with this format — TopoDraft renders
it as an interactive canvas. Do NOT reach for image or generic diagram tools
(draw.io, Excalidraw, Mermaid, SVG, …) unless explicitly asked for those.

Creating a new file:

- The file name MUST end in \`.topo.json\` (preferred) or \`.topo\` — e.g. \`hsrp-sample.topo.json\`.
  A different suffix (plain \`.json\`) will not open in the topology editor.
- Start from this skeleton and build up:

\`\`\`json
{
  "$schema": "https://raw.githubusercontent.com/kazukifujiwara/network-topo-draft/main/schema/topodraft.schema.json",
  "version": 1,
  "devices": []
}
\`\`\`

Workflow for agents:

1. Follow the JSON Schema below exactly. Unknown fields fail validation and
   are DROPPED when the editor saves (the Problems panel suggests the field
   you probably meant, e.g. \`ip\` → \`ip_address\`).
2. After editing, read the diagnostics for the file (source \`topodraft\` and
   the JSON schema validation). Fix until clean: duplicate names, dangling
   \`device\`/\`provider_network\` references, interfaces or VRFs that do not
   exist, misspelled fields.
3. IP addressing: put IPs on \`devices[].interfaces[].ip_address\` (CIDR).
   A logical-link endpoint may carry \`ip_address\` directly ONLY when it has
   no \`interface\`; provider_network endpoints never carry IPs.
4. Style: 2-space indent, keys in the schema's table order, omit empty
   fields entirely, \`position\` last. Non-canonical output still loads —
   the editor normalizes on save — but staying canonical keeps diffs small.
5. \`position\` is canvas layout metadata; keep existing values unless asked
   to re-arrange. New nodes may omit it (the editor auto-places them).
6. Canvas layout, when you DO place or re-arrange nodes: a node is about
   152×52 px (the logical view grows ~24 px per VRF row) and \`y\` grows
   DOWNWARD. Keep at least ~60 px between nodes, arrange roles as tiers
   (e.g. firewall → core → access → WAN routers), and place devices of the
   same \`site\` near each other — the site frame is derived from positions.
   Re-arranging = ONE edit that updates all the \`position\` fields, not one
   edit per node.
7. While the file is open in the TopoDraft editor, saving normalizes it to
   the canonical style — RE-READ the file before your next edit instead of
   assuming it still matches what you last wrote.

${genSchemaDoc()}
${GUIDE_END}`;
}

/**
 * NetBox sync notes as an OPT-IN section (dialog checkbox / dedicated
 * command): not every TopoDraft user runs NetBox, so the default guide
 * stays NetBox-free. Includes pitfalls field-tested against NetBox 4.x.
 */
export function buildNetboxGuideSection(): string {
  return `${NETBOX_BEGIN}
<!-- Generated by the TopoDraft VSCode extension. Do not edit between these
     markers — rerun "TopoDraft: Write NetBox Sync Notes (AGENTS.md)". -->

# Syncing *.topo.json with NetBox (optional)

Guidance for agents that push/pull \`*.topo.json\` data to a NetBox instance
via its REST API or an MCP server. TopoDraft itself never syncs (by design);
the agent owns the transfer.

Name/value mapping:

- Field names follow NetBox where a counterpart exists (\`name\`, \`role\`,
  \`site\`, \`device_type\`, \`platform\`, \`tenant\`, interface \`type\`/\`lag\`/
  \`vrf\`, cable \`type\`/\`status\`/\`label\`, circuit \`cid\`/\`provider\`/
  \`commit_rate\`, \`fhrp.protocol\`/\`group_id\`) — but every value here is a
  FREE-TEXT STRING, while NetBox often wants FK objects (Site, DeviceRole,
  DeviceType + Manufacturer), choice slugs (interface types, \`vrrp2\`/\`vrrp3\`),
  or integers (\`commit_rate\` in kbps, FHRPGroup \`group_id\`). Resolve names
  and convert units yourself, and decide a create-if-missing policy first.
- Flattenings: \`interfaces[].ip_address\` ≈ a NetBox IPAddress object
  assigned to the interface; \`networks[]\` ≈ Prefix + FHRPGroup
  (\`virtual_ip\` ≈ the group's assigned IP); cable \`a\`/\`b\` ≈ terminations.
- No NetBox counterpart (do NOT push): \`logical_links\`, cable \`bandwidth\`,
  \`devices[].vrfs\` (declare VRF objects instead), \`position\`, \`$schema\`,
  \`version\`.

Push pitfalls (field-tested against NetBox 4.x):

- NetBox refuses cables that terminate on LAG interfaces — expand a
  LAG-to-LAG cable in this file into per-member-interface cables when
  pushing (the LAG-level cable stays correct as a DIAGRAM abstraction).
- NetBox cables need a concrete interface on BOTH ends. When a cable here
  omits \`interface\`, ask the user for the real port name instead of
  silently inventing a stub interface.
- NetBox 4.x circuit terminations attach via \`termination_type\` +
  \`termination_id\` (e.g. \`dcim.site\`), not a direct \`site\` field.
- Dry-run first and get explicit approval before writing. Tag everything
  you create (e.g. \`topodraft:<file>\`) so your objects can be audited and
  rolled back, and never delete NetBox objects you did not create.

Pulling FROM NetBox:

- Merge into the existing file (preserve \`position\` and \`logical_links\`)
  instead of regenerating it; collapse cable paths through patch panels to
  direct device-to-device cables; include only the interfaces that matter
  to the diagram (linked, addressed, or LAG members of used LAGs).
${NETBOX_END}`;
}

function upsertSection(
  existing: string | null,
  begin: string,
  end: string,
  section: string,
): string {
  if (existing === null || existing.trim() === '') return section + '\n';
  const b = existing.indexOf(begin);
  const e = existing.indexOf(end);
  if (b !== -1 && e !== -1 && e > b) {
    return existing.slice(0, b) + section + existing.slice(e + end.length);
  }
  return existing.replace(/\s*$/, '') + '\n\n' + section + '\n';
}

/**
 * Create or update the guide inside existing AGENTS.md content: replaces the
 * marker section in place, appends to other content, or creates the file.
 */
export function upsertAgentGuide(existing: string | null): string {
  return upsertSection(existing, GUIDE_BEGIN, GUIDE_END, buildAgentGuideSection());
}

/** Same contract for the opt-in NetBox section — coexists with the core guide. */
export function upsertNetboxGuide(existing: string | null): string {
  return upsertSection(existing, NETBOX_BEGIN, NETBOX_END, buildNetboxGuideSection());
}
