/**
 * AGENTS.md generator: writes the *.topo.json contract where coding-agent
 * harnesses (Claude Code, Copilot, …) discover instructions automatically.
 * This is how an agent learns the format BEFORE its first edit — the
 * Problems panel (schema + did-you-mean diagnostics) covers the after.
 *
 * Pure string logic here; the command wiring lives in commands.ts.
 */
import { genSchemaDoc } from '@topodraft/core';

export const GUIDE_BEGIN = '<!-- topodraft:agent-guide:begin -->';
export const GUIDE_END = '<!-- topodraft:agent-guide:end -->';

export function buildAgentGuideSection(): string {
  return `${GUIDE_BEGIN}
<!-- Generated by the TopoDraft VSCode extension. Do not edit between these
     markers — rerun "TopoDraft: Write AI Agent Guide (AGENTS.md)" to update. -->

# Editing *.topo.json files (TopoDraft)

Files matching \`*.topo.json\` are network topology documents edited BOTH by
humans on the TopoDraft canvas and by agents as text. The text document is
the single source of truth — your edits appear on the canvas live.

When asked to create, draw, or update a NETWORK DIAGRAM or topology in this
workspace, produce a \`*.topo.json\` file with this format — TopoDraft renders
it as an interactive canvas. Do NOT reach for image or generic diagram tools
(draw.io, Excalidraw, Mermaid, SVG, …) unless explicitly asked for those.

Creating a new file:

- The file name MUST end in \`.topo.json\` (preferred) or \`.topo\` — e.g. \`hsrp-sample.topo.json\`.
  A different suffix (plain \`.json\`) will not open in the topology editor.
- Start from this skeleton and build up:

\`\`\`json
{
  "$schema": "https://raw.githubusercontent.com/kazukifujiwara/network-topo-draft/main/schema/topodraft.schema.json",
  "version": 1,
  "devices": []
}
\`\`\`

Workflow for agents:

1. Follow the JSON Schema below exactly. Unknown fields fail validation and
   are DROPPED when the editor saves (the Problems panel suggests the field
   you probably meant, e.g. \`ip\` → \`ip_address\`).
2. After editing, read the diagnostics for the file (source \`topodraft\` and
   the JSON schema validation). Fix until clean: duplicate names, dangling
   \`device\`/\`provider_network\` references, interfaces or VRFs that do not
   exist, misspelled fields.
3. IP addressing: put IPs on \`devices[].interfaces[].ip_address\` (CIDR).
   A logical-link endpoint may carry \`ip_address\` directly ONLY when it has
   no \`interface\`; provider_network endpoints never carry IPs.
4. Style: 2-space indent, keys in the schema's table order, omit empty
   fields entirely, \`position\` last. Non-canonical output still loads —
   the editor normalizes on save — but staying canonical keeps diffs small.
5. \`position\` is canvas layout metadata; keep existing values unless asked
   to re-arrange. New nodes may omit it (the editor auto-places them).

NetBox mapping notes (when you sync this file with NetBox via API/MCP):

- Field names follow NetBox where a counterpart exists (\`name\`, \`role\`,
  \`site\`, \`device_type\`, \`platform\`, \`tenant\`, interface \`type\`/\`lag\`/
  \`vrf\`, cable \`type\`/\`status\`/\`label\`, circuit \`cid\`/\`provider\`/
  \`commit_rate\`, \`fhrp.protocol\`/\`group_id\`) — but every value here is a
  FREE-TEXT STRING, while NetBox often wants FK objects (Site, DeviceRole,
  DeviceType + Manufacturer), choice slugs (interface types, \`vrrp2\`/\`vrrp3\`),
  or integers (\`commit_rate\` in kbps, FHRPGroup \`group_id\`). Resolve names
  and convert units yourself, and decide a create-if-missing policy first.
- Flattenings: \`interfaces[].ip_address\` ≈ a NetBox IPAddress object
  assigned to the interface; \`networks[]\` ≈ Prefix + FHRPGroup
  (\`virtual_ip\` ≈ the group's assigned IP); cable \`a\`/\`b\` ≈ terminations.
- No NetBox counterpart (do NOT push): \`logical_links\`, cable \`bandwidth\`,
  \`devices[].vrfs\` (declare VRF objects instead), \`position\`, \`$schema\`,
  \`version\`.
- Identity is name-based here. Track your own mapping (e.g. a NetBox tag)
  so a rename in one system is not mistaken for delete + create, and only
  delete NetBox objects you created from this file.
- Pulling FROM NetBox: merge into the existing file (preserve \`position\`
  and \`logical_links\`) instead of regenerating it; collapse cable paths
  through patch panels to direct device-to-device cables; include only the
  interfaces that matter to the diagram.

${genSchemaDoc()}
${GUIDE_END}`;
}

/**
 * Create or update the guide inside existing AGENTS.md content: replaces the
 * marker section in place, appends to other content, or creates the file.
 */
export function upsertAgentGuide(existing: string | null): string {
  const section = buildAgentGuideSection();
  if (existing === null || existing.trim() === '') return section + '\n';
  const begin = existing.indexOf(GUIDE_BEGIN);
  const end = existing.indexOf(GUIDE_END);
  if (begin !== -1 && end !== -1 && end > begin) {
    return existing.slice(0, begin) + section + existing.slice(end + GUIDE_END.length);
  }
  return existing.replace(/\s*$/, '') + '\n\n' + section + '\n';
}
