/**
 * AGENTS.md generator: writes the *.topo.json contract where coding-agent
 * harnesses (Claude Code, Copilot, …) discover instructions automatically.
 * This is how an agent learns the format BEFORE its first edit — the
 * Problems panel (schema + did-you-mean diagnostics) covers the after.
 *
 * Pure string logic here; the command wiring lives in commands.ts.
 */
import { genSchemaDoc } from '@topodraft/core';

export const GUIDE_BEGIN = '<!-- topodraft:agent-guide:begin -->';
export const GUIDE_END = '<!-- topodraft:agent-guide:end -->';
/** Optional, independently managed section — not every user runs NetBox. */
export const NETBOX_BEGIN = '<!-- topodraft:netbox-guide:begin -->';
export const NETBOX_END = '<!-- topodraft:netbox-guide:end -->';

export function buildAgentGuideSection(): string {
  return `${GUIDE_BEGIN}
<!-- Generated by the TopoDraft VSCode extension. Do not edit between these
     markers — rerun "TopoDraft: Write AI Agent Guide (AGENTS.md)" to update. -->

# Editing *.topo.json files (TopoDraft)

Files matching \`*.topo.json\` are network topology DIAGRAM documents edited
BOTH by humans on the TopoDraft canvas and by agents as text. The canvas is
a live view of the text — edit the file and the drawing follows. The file
is authoritative for the DIAGRAM only, never for the network itself: if the
organization maintains a configuration/inventory system (e.g. NetBox), that
system — not this file — is the network's source of truth, and this file is
a view derived from or feeding it.

When asked to create, draw, or update a NETWORK DIAGRAM or topology in this
workspace, produce a \`*.topo.json\` file with this format — TopoDraft renders
it as an interactive canvas. Prefer this format over image files or other
diagram formats; those are the right choice only when the user explicitly
asks for one of them.

Creating a new file:

- The file name MUST end in \`.topo.json\` (preferred) or \`.topo\` — e.g. \`hsrp-sample.topo.json\`.
  A different suffix (plain \`.json\`) will not open in the topology editor.
- Start from this skeleton and build up:

\`\`\`json
{
  "$schema": "https://raw.githubusercontent.com/kazukifujiwara/network-topo-draft/main/schema/topodraft.schema.json",
  "version": 1,
  "devices": []
}
\`\`\`

Workflow for agents:

1. Follow the JSON Schema below exactly. Unknown fields fail validation and
   are DROPPED when the editor saves (the Problems panel suggests the field
   you probably meant, e.g. \`ip\` → \`ip_address\`).
2. After editing, validate. If your environment surfaces the editor's
   diagnostics (the VSCode Problems panel: source \`topodraft\` plus JSON
   schema validation), read them and fix until clean; if you run headless,
   check the file against the JSON Schema below yourself. Either way watch
   for: duplicate names, dangling \`device\`/\`provider_network\` references,
   interfaces or VRFs that do not exist, misspelled fields.
3. IP addressing: put IPs on \`devices[].interfaces[].ip_address\` (CIDR).
   A logical-link endpoint may carry \`ip_address\` directly ONLY when it has
   no \`interface\`; provider_network endpoints never carry IPs.
4. Style: 2-space indent, keys in the schema's table order, omit empty
   fields entirely, \`position\` last. Non-canonical output still loads —
   the editor normalizes on save — but staying canonical keeps diffs small.
5. \`position\` is canvas layout metadata; keep existing values unless asked
   to re-arrange. New nodes may omit it (the editor auto-places them).
6. Canvas layout, when you DO place or re-arrange nodes: a node is about
   152×52 px (the logical view grows ~24 px per VRF row) and \`y\` grows
   DOWNWARD. Keep at least ~60 px between nodes, arrange roles as tiers
   (e.g. firewall → core → access → WAN routers), and place devices of the
   same \`site\` near each other — the site frame is derived from positions.
   Re-arranging = ONE edit that updates all the \`position\` fields, not one
   edit per node.
7. While the file is open in the TopoDraft editor, saving normalizes it to
   the canonical style — RE-READ the file before your next edit instead of
   assuming it still matches what you last wrote.

${genSchemaDoc()}
${GUIDE_END}`;
}

/**
 * NetBox REFERENCE notes as an OPT-IN section (dialog checkbox / dedicated
 * command): not every TopoDraft user runs NetBox, so the default guide
 * stays NetBox-free. Deliberately read-only — the extension does not
 * endorse automated writes to NetBox (Kazuki's ruling: users who want
 * write automation add their own instructions outside the markers).
 */
export function buildNetboxGuideSection(): string {
  return `${NETBOX_BEGIN}
<!-- Generated by the TopoDraft VSCode extension. Do not edit between these
     markers — rerun "TopoDraft: Write NetBox Reference Notes (AGENTS.md)". -->

# Referencing NetBox data in *.topo.json (optional)

Notes for agents that READ data from a NetBox instance (REST API or an MCP
server) to create or update \`*.topo.json\` files. WRITING topology data back
to NetBox is intentionally OUT OF SCOPE for this guide: TopoDraft never
syncs, and this extension does not endorse automated writes. If you decide
to automate them in your own environment, add your own instructions to
AGENTS.md OUTSIDE the TopoDraft marker sections, at your own risk. When
reference is all you need, use a read-only API token.

How NetBox objects map onto this format:

- Field names follow NetBox where a counterpart exists (\`name\`, \`role\`,
  \`site\`, \`device_type\`, \`platform\`, \`tenant\`, interface \`type\`/\`lag\`/
  \`vrf\`, cable \`type\`/\`status\`/\`label\`, circuit \`cid\`/\`provider\`/
  \`commit_rate\`, \`fhrp.protocol\`/\`group_id\`). Values HERE are free-text
  strings — flatten NetBox's FK objects, choice slugs, and integers into
  readable strings (e.g. \`commit_rate\` 1000000 kbps → \`"1Gbps"\`).
- Flattenings: a NetBox IPAddress assigned to an interface →
  \`interfaces[].ip_address\`; Prefix + FHRPGroup → one \`networks[]\` entry
  (the group's assigned IP → \`fhrp.virtual_ip\`); cable terminations →
  the \`a\`/\`b\` endpoints.
- TopoDraft-only data NetBox knows nothing about: \`logical_links\`, cable
  \`bandwidth\`, \`devices[].vrfs\`, \`position\`, \`$schema\`, \`version\`.
  NEVER drop these when refreshing a file from NetBox.

Pulling from NetBox into a file:

- Scope the query first (site / tenant / tag) — a \`*.topo.json\` is one
  diagram, not the whole database.
- Merge into the existing file, preserving \`position\`, \`logical_links\`,
  and other TopoDraft-only data — do not regenerate from scratch.
- Collapse cable paths that run through patch panels (front/rear ports)
  into direct device-to-device cables.
- Include only the interfaces that matter to the diagram (linked,
  addressed, or LAG members of used LAGs) — not all 48 ports.
- NetBox has no L3-adjacency object: derive \`logical_links\` and
  \`networks[]\` yourself where useful (FHRPGroup + Prefix → a segment).
${NETBOX_END}`;
}

function upsertSection(
  existing: string | null,
  begin: string,
  end: string,
  section: string,
): string {
  if (existing === null || existing.trim() === '') return section + '\n';
  const b = existing.indexOf(begin);
  const e = existing.indexOf(end);
  if (b !== -1 && e !== -1 && e > b) {
    return existing.slice(0, b) + section + existing.slice(e + end.length);
  }
  return existing.replace(/\s*$/, '') + '\n\n' + section + '\n';
}

/**
 * Create or update the guide inside existing AGENTS.md content: replaces the
 * marker section in place, appends to other content, or creates the file.
 */
export function upsertAgentGuide(existing: string | null): string {
  return upsertSection(existing, GUIDE_BEGIN, GUIDE_END, buildAgentGuideSection());
}

/** Same contract for the opt-in NetBox section — coexists with the core guide. */
export function upsertNetboxGuide(existing: string | null): string {
  return upsertSection(existing, NETBOX_BEGIN, NETBOX_END, buildNetboxGuideSection());
}
